In [ ]:
import numpy as np

CURVE_CENTER = 80

grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])

def curve(grades):
    average = grades.mean()
    change = CURVE_CENTER - average
    new_grades = grades + change
    return np.clip(new_grades, grades, 100)

curve(grades)


In [ ]:
import numpy as np
type(np)

In [ ]:
%whos


In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
## tset

In [ ]:
### Pandas

In [2]:
import pandas as pd

df = pd.DataFrame(
    {
        "Name": ["Hibriten",
         "Hen",
         "Timbered Ridge"
         ],
         "Elevation":[2250, 2000, 1500]
    }
)

df["Name"]

0          Hibriten
1               Hen
2    Timbered Ridge
Name: Name, dtype: object

In [6]:
df.Elevation>2000
test = df[df.Elevation > 2000]
type(test)

pandas.core.frame.DataFrame

In [8]:
A = df["Elevation"]
type(A)
AB = df[["Elevation", "Name"]]
type(AB)

pandas.core.frame.DataFrame

In [10]:
df[[True, False, True]]

Name  Elevation
0        Hibriten       2250
2  Timbered Ridge       1500

In [ ]:
df.describe()

In [ ]:
layer = pd.read_csv(r"")
layer.head(9)
#layer[:5]


In [ ]:
layer.to_excel(r"")

In [ ]:
pip install openpyxl

In [ ]:
layer.info()

In [ ]:
cat = layer["NAME_CATGY"]
cat

In [ ]:
type(cat)

In [ ]:
cat.shape

In [ ]:
status = layer[["EO_STATUS", "NAME_CATGY"]]
status

In [ ]:
filtered = layer[layer["NAME_CATGY"] == "Natural Community"]
filtered

In [ ]:
confidenceLevel = layer[layer["ACCURACY"].isin(["2-High", "4-Low"])]
confidenceLevel

In [ ]:
selectionOne = layer[layer["EO_RANK"]== "E"]
selectionOne

In [ ]:
selectionTwo = layer[layer["NAME_CATGY"].notna()]
selectionTwo

In [ ]:
sampleLoc = layer.loc[layer["NAME_CATGY"]== "Natural Community", "EO_RANK"]
sampleLoc

In [ ]:
sampleIloc = layer.iloc[2:4, 2:6]
sampleIloc

In [ ]:
layer = pd.read_csv(r"C:\Users\yuri7100\Desktop\Data.csv")
layer.head(9)
#layer[:5]

In [ ]:
selectAccuracy = layer[layer["ACCURACY"] == "3-Medium"]
selectAccuracy

In [ ]:
selectObsRank = layer[(layer["LAST_OBS"] == "2007-05-15") & (layer["NAME_CATGY"]  == "Animal")]
selectObsRank

In [ ]:
selectLoc = layer.loc[layer["EO_STATUS"] == "Historical", "LAST_OBS"]
selectLoc

In [ ]:
selectIloc = layer.iloc[:5, :3]
selectIloc

In [ ]:
layer["Elevation"] = layer["Shape_Length"] / 10

In [ ]:
layer.head()

In [ ]:
#layer["Dates"] = (layer["LAST_OBS"] + layer["DATA_DATE"])
layer.head()

In [ ]:
layer["EO_ID"].mean()

In [ ]:
layer[["EO_ID", "Shape_Length"]].median()

In [ ]:
layer.agg(
    {
        "EO_ID": ["min", "max", "median", "skew"],
        "Shape_Length": ["min", "max", "median", "mean"],
    }
 )

In [ ]:
layer.head(3)

In [ ]:
layer.groupby("ACCURACY").mean()

In [ ]:
layer.groupby("ACCURACY")["Elevation"].mean()

In [ ]:
layer.groupby(["ACCURACY","EO_ID"])["Elevation"].mean()

In [ ]:
layer.head()

In [ ]:
mtns = {
    "Hibriten": 2300,
    "Hen": 1850,
    "Timbered Ridge": 1500
}

mountains = pd.Series(mtns)
mountains

In [ ]:
output = mountains*2
output

In [ ]:
mountains.get("Hibriten")

In [ ]:
import sys
sys.path

In [ ]:
import os
os?

In [ ]:
import numpy as np
CURVE_CENTER = 80

grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])

def curve(grades):
     average = grades.mean()
     change = CURVE_CENTER - average
     new_grades = grades + change
     return np.clip(new_grades, grades, 100)
curve(grades)

In [ ]:
temperatures = np.array([
        29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
        12.6, 49.9, 38.6, 31.3, 9.2, 22.2
   ]).reshape(2,2,3)

temperatures

In [ ]:
table = np.array([
        [5, 3, 7, 1],
        [2, 6, 7 ,9],
        [1, 1, 1, 1],
        [4, 3, 2, 0],
   ])
print(table.max(axis=0))
print(table.max(axis=1))

In [ ]:
table.sum()

In [ ]:
square = np.array([
        [16, 3, 2, 13],
        [5, 10, 11, 8],
        [9, 6, 7, 12],
        [4, 15, 14, 1]
   ])

for i in range(4):
    assert square[:, i].sum() == 34
square.ndim

In [ ]:
np.__version__

In [ ]:
import numpy as np

arr = np.array([[2200, 1850], 
        [2000, 1980]])
arr[0][1]

arr.ndim


In [58]:
arr2 = np.array([[[1, 2, 3], 
                  [4, 5, 6]], 
                  [[1, 2, 3], 
                  [4, 5, 6]]])

print(arr2.ndim)
print(arr2.sum(axis=0))
print(arr2.sum(axis=1))
print(arr2.sum(axis=2))

3
[[ 2  4  6]
 [ 8 10 12]]
[[5 7 9]
 [5 7 9]]
[[ 6 15]
 [ 6 15]]


In [61]:
test1 = np.zeros((10,10))
test1.dtype
test1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [65]:
x = np.array([[1,2],[3,4]])
x.sum(axis=1)

array([3, 7])

In [77]:
import numpy as np

a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])
#print(a)

lastrow = a[2]
#print(lastrow.dtype)

firstcol = a[:, 0]
a_gt_5 = a > 5
#print(a_gt_5)

print(a[a>5])



[ 6  7  8  9 10 11]


In [85]:
import pandas as pd

table = pd.read_csv(r"C:\Users\yuri7100\Desktop\Velocity_Feeds\Five.27.2021.csv", encoding="latin1")
table.head()

Date (MM/DD/YYYY) Time (HH:mm:ss)  Time (Fract. Sec) Site Name  \
0         5/27/2021         9:05:23                  0        PK   
1         5/27/2021         9:05:26                  0        PK   
2         5/27/2021         9:05:29                  0        PK   
3         5/27/2021         9:05:32                  0        PK   
4         5/27/2021         9:05:35                  0        PK   

   Chlorophyll RFU  Chlorophyll ug/L  Cond µS/cm  Depth m  fDOM QSU  fDOM RFU  \
0             0.39              1.63        36.3    0.233     11.50      3.79   
1             0.39              1.63        36.3    0.233     11.51      3.79   
2             0.37              1.55        36.3    0.233     11.51      3.79   
3             0.35              1.49        36.3    0.233     11.50      3.78   
4             0.37              1.56        36.3    0.233     11.51      3.79   

   ...  pH mV  Temp °C  Vertical Position m  GPS Latitude °  GPS Longitude °  \
0  ...  -30.5    9.947                0.228        44.75709        -122.3655   
1  ...  -30.4    9.948                0.228        44.75709        -122.3655   
2  ...  -30.3    9.947                0.230        44.75708        -122.3655   
3  ...  -30.2    9.947                0.243        44.75708        -122.3655   
4  ...  -30.2    9.943                0.227        44.75708        -122.3655   

   Altitude m  Battery V  Cable Pwr V  Barometer mmHg  Depth ft   
0       307.8       5.93         12.1           736.4    0.76424  
1       309.6       5.93         12.1           736.4    0.76424  
2       311.5       5.93         12.1           736.3    0.76424  
3       311.0       5.93         12.1           736.4    0.76424  
4       309.7       5.93         12.1           736.4    0.76424  

[5 rows x 34 columns]

In [96]:
latLong = table[["GPS Latitude °", "GPS Longitude °"]]
latLong

GPS Latitude °  GPS Longitude °
0          44.75709        -122.3655
1          44.75709        -122.3655
2          44.75708        -122.3655
3          44.75708        -122.3655
4          44.75708        -122.3655
..              ...              ...
166        44.79101        -122.7501
167        44.79101        -122.7501
168        44.79101        -122.7501
169        44.79101        -122.7501
170        44.79101        -122.7501

[171 rows x 2 columns]

In [15]:
table.to_json(r"C:\Users\yuri7100\Desktop\Velocity_Feeds\test.json", orient="index")

In [6]:
import numpy as np
x = np.ndarray((6,4))
x

array([[6.23042070e-307, 2.22523004e-307, 1.24610994e-306,
        9.34605037e-307],
       [2.33648883e-307, 1.60219578e-306, 9.34605037e-307,
        6.23059726e-307],
       [8.90104239e-307, 1.33511290e-306, 2.55899112e-307,
        3.56033887e-307],
       [1.11261027e-306, 1.11261502e-306, 1.42410839e-306,
        7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 1.37961302e-306,
        9.79094970e-307],
       [1.78019354e-306, 6.89810244e-307, 9.34609111e-307,
        2.56765117e-312]])

In [8]:
len(x[:,1])

6

In [10]:
len(x[2:,2:])

4

In [11]:
x[2:,2:]

array([[2.55899112e-307, 3.56033887e-307],
       [1.42410839e-306, 7.56597770e-307],
       [1.37961302e-306, 9.79094970e-307],
       [9.34609111e-307, 2.56765117e-312]])

In [13]:
x = np.zeros((6,4))
typ = x[-1,-1]
typ.dtype

dtype('float64')