In [ ]:
import numpy as np

CURVE_CENTER = 80

grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])

def curve(grades):
    average = grades.mean()
    change = CURVE_CENTER - average
    new_grades = grades + change
    return np.clip(new_grades, grades, 100)

curve(grades)


In [ ]:
import numpy as np
type(np)

In [ ]:
%whos


In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
## tset

In [6]:
### Pandas

In [ ]:
import pandas as pd

df = pd.DataFrame(
    {
        "Name": ["Hibriten",
         "Hen",
         "Timbered Ridge"
         ],
         "Elevation":[2250, 2000, 1500]
    }
)

df["Name"]

In [ ]:
df.describe()

In [ ]:
layer = pd.read_csv(r"")
layer.head(9)
#layer[:5]


In [ ]:
layer.to_excel(r"")

In [ ]:
pip install openpyxl

In [ ]:
layer.info()

In [ ]:
cat = layer["NAME_CATGY"]
cat

In [ ]:
type(cat)

In [ ]:
cat.shape

In [ ]:
status = layer[["EO_STATUS", "NAME_CATGY"]]
status

In [ ]:
filtered = layer[layer["NAME_CATGY"] == "Natural Community"]
filtered

In [ ]:
confidenceLevel = layer[layer["ACCURACY"].isin(["2-High", "4-Low"])]
confidenceLevel

In [ ]:
selectionOne = layer[layer["EO_RANK"]== "E"]
selectionOne

In [ ]:
selectionTwo = layer[layer["NAME_CATGY"].notna()]
selectionTwo

In [ ]:
sampleLoc = layer.loc[layer["NAME_CATGY"]== "Natural Community", "EO_RANK"]
sampleLoc

In [ ]:
sampleIloc = layer.iloc[2:4, 2:6]
sampleIloc

In [ ]:
layer = pd.read_csv(r"C:\Users\yuri7100\Desktop\Data.csv")
layer.head(9)
#layer[:5]

In [ ]:
selectAccuracy = layer[layer["ACCURACY"] == "3-Medium"]
selectAccuracy

In [ ]:
selectObsRank = layer[(layer["LAST_OBS"] == "2007-05-15") & (layer["NAME_CATGY"]  == "Animal")]
selectObsRank

In [ ]:
selectLoc = layer.loc[layer["EO_STATUS"] == "Historical", "LAST_OBS"]
selectLoc

In [ ]:
selectIloc = layer.iloc[:5, :3]
selectIloc

In [ ]:
layer["Elevation"] = layer["Shape_Length"] / 10

In [ ]:
layer.head()

In [ ]:
#layer["Dates"] = (layer["LAST_OBS"] + layer["DATA_DATE"])
layer.head()

In [ ]:
layer["EO_ID"].mean()

In [ ]:
layer[["EO_ID", "Shape_Length"]].median()

In [ ]:
layer.agg(
    {
        "EO_ID": ["min", "max", "median", "skew"],
        "Shape_Length": ["min", "max", "median", "mean"],
    }
 )

In [ ]:
layer.head(3)

In [ ]:
layer.groupby("ACCURACY").mean()

In [ ]:
layer.groupby("ACCURACY")["Elevation"].mean()

In [ ]:
layer.groupby(["ACCURACY","EO_ID"])["Elevation"].mean()

In [ ]:
layer.head()

In [ ]:
mtns = {
    "Hibriten": 2300,
    "Hen": 1850,
    "Timbered Ridge": 1500
}

mountains = pd.Series(mtns)
mountains

In [ ]:
output = mountains*2
output

In [ ]:
mountains.get("Hibriten")

In [ ]:
import sys
sys.path

In [ ]:
import os
os?

In [6]:
import numpy as np
CURVE_CENTER = 80

grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])

def curve(grades):
     average = grades.mean()
     change = CURVE_CENTER - average
     new_grades = grades + change
     return np.clip(new_grades, grades, 100)
curve(grades)

array([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

In [10]:
temperatures = np.array([
        29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
        12.6, 49.9, 38.6, 31.3, 9.2, 22.2
   ]).reshape(2,2,3)

temperatures

array([[[29.3, 42.1, 18.8],
        [16.1, 38. , 12.5]],

       [[12.6, 49.9, 38.6],
        [31.3,  9.2, 22.2]]])

In [12]:
table = np.array([
        [5, 3, 7, 1],
        [2, 6, 7 ,9],
        [1, 1, 1, 1],
        [4, 3, 2, 0],
   ])
print(table.max(axis=0))
print(table.max(axis=1))

[5 6 7 9]
[7 9 1 4]


In [13]:
table.sum()

53